name: "Update Flake Deps"
on:
  push:
  schedule:
    - cron: '17 10-17 * * *'

jobs:
  update-flake-deps:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v13
      with:
        install_url: https://github.com/numtide/nix-unstable-installer/releases/download/nix-2.4pre20210415_76980a1/install
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Update flake deps
      run: nix flake update
    - name: Commit
      run: |
        git commit -m "chore(deps): update flake deps"
        git push
