name: "Nix"
on:
  workflow_dispatch:
  pull_request:
    branches: [ master, release-1.0 ]
  push:
    branches: [ master, release-1.0 ]
jobs:
  brp-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-cargo-integration
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Tests
      run: nix build .#platformChecks.brp

  naersk-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-cargo-integration
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Tests
      run: nix build .#platformChecks.naersk

  crate2nix-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-cargo-integration
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Tests
      run: nix build .#platformChecks.crate2nix

  dream2nix-tests:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout repo
      uses: actions/checkout@v2
    - name: Install nix
      uses: cachix/install-nix-action@v16
      with:
        extra_nix_config: |
          experimental-features = nix-command flakes
        nix_path: nixpkgs=channel:nixos-unstable
    - name: Setup cachix
      uses: cachix/cachix-action@v10
      with:
        name: nix-cargo-integration
        authToken: '${{ secrets.CACHIX_AUTH_TOKEN }}'
    - name: Tests
      run: nix build .#platformChecks.dream2nix
